### ISSUE TITLE
README.md change needed for PHPCBF path variable

### ISSUE THREAD

**Issue by xavortm** [praem90/nvim-phpcsf#6]
Hi!

I was setting up the plugin and found that the variable shown in the docs is different from the one in the codebase.

The readme says to set `let g:nvim_phpcs_config_phpcbf_path = 'phpcbf'`

But I see in here https://github.com/praem90/nvim-phpcsf/blob/master/lua/phpcs/init.lua#L15 the variable in use is "paths" instead of "path".

So the correct variable should be `let g:nvim_phpcs_config_phpcbf_paths = 'phpcbf'` instead.

Changing this fixed my issue of "phpcbf" not found error.

**Comment by praem90** [comment]
Thanks for raising the issue.. I'll fix this
